name: CI

on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - main

env:
  ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
  ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
  ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.PGP_SECRET }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.PGP_KEY_ID }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.PGP_PASSPHRASE }}

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download Java JDK
        uses: typelevel/download-java@v2
        id: download-java
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Java JDK
        uses: actions/setup-java@v3.11.0
        with:
          distribution: jdkfile
          java-version: 11
          jdkFile: ${{ steps.download-java.outputs.jdkFile }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build & Test
        run: ./gradlew build --info

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Publish Test Results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: '**/build/test-results/*/TEST-*.xml'

      - name: Publish To Sonatype
        if: github.event_name != 'pull_request' && (startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main')
        run: ./gradlew publishAllPublicationsToMavenCentral


    services:
      nunjucks-renderer:
        image: ghcr.io/opencastsoftware/govuk-nunjucks-renderer:0.1.4
        ports:
          - 3000:3000
